///////////////////////////////////////////////////////////////////////////////
//
//  Copyright (2018) Alexander Stukowski
//
//  This file is part of OVITO (Open Visualization Tool).
//
//  OVITO is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation; either version 2 of the License, or
//  (at your option) any later version.
//
//  OVITO is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
///////////////////////////////////////////////////////////////////////////////

#include <plugins/particles/gui/ParticlesGui.h>
#include <plugins/particles/modifier/analysis/StructureIdentificationModifier.h>
#include <plugins/stdobj/series/DataSeriesObject.h>
#include <gui/properties/ModifierPropertiesEditor.h>
#include "StructureListParameterUI.h"

namespace Ovito { namespace Particles { OVITO_BEGIN_INLINE_NAMESPACE(Modifiers) OVITO_BEGIN_INLINE_NAMESPACE(Analysis)

IMPLEMENT_OVITO_CLASS(StructureListParameterUI);

/******************************************************************************
* Constructor.
******************************************************************************/
StructureListParameterUI::StructureListParameterUI(PropertiesEditor* parentEditor, bool showCheckBoxes)
	: RefTargetListParameterUI(parentEditor, PROPERTY_FIELD(StructureIdentificationModifier::structureTypes)),
	  _showCheckBoxes(showCheckBoxes)
{
	connect(tableWidget(220), &QTableWidget::doubleClicked, this, &StructureListParameterUI::onDoubleClickStructureType);
	connect(parentEditor, &PropertiesEditor::contentsReplaced, tableWidget(), &QTableView::resizeRowsToContents);
	tableWidget()->setAutoScroll(false);

	// Update the structure count and fraction columns of the data model whenever the structure identification
	// modifier has generated new results.
	if(ModifierPropertiesEditor* modifierEditor = dynamic_object_cast<ModifierPropertiesEditor>(parentEditor)) {
		connect(modifierEditor, &ModifierPropertiesEditor::modifierEvaluated, this, [this]() {
			updateStructureCounts();
			_model->updateColumns(2, 3);
		});
	}
}

/******************************************************************************
* This method is called when a new editable object has been activated.
******************************************************************************/
void StructureListParameterUI::resetUI()
{
	// Refresh our internal structure count list. 
	updateStructureCounts();

	// Call base implementation.
	RefTargetListParameterUI::resetUI();

	// Clear initial selection by default.
	tableWidget()->selectionModel()->clear();
}

/******************************************************************************
* Obtains the current structure counts from the pipeline. 
******************************************************************************/
void StructureListParameterUI::updateStructureCounts()
{
	if(ModifierPropertiesEditor* modifierEditor = dynamic_object_cast<ModifierPropertiesEditor>(editor())) {
		if(ModifierApplication* modApp = modifierEditor->modifierApplication()) {
		
			// Get the current data pipeline output generated by the modifier.
			const PipelineFlowState& state = modifierEditor->getModifierOutput();

			// Access the data series in the pipeline state containing the structure counts.
			if(const DataSeriesObject* series = state.getObjectBy<DataSeriesObject>(modApp, QStringLiteral("structures"))) {
				_structureCounts = series->getYStorage();
				if(_structureCounts && _structureCounts->dataType() == PropertyStorage::Int64)
					return;
			}
		}
	}
	_structureCounts.reset();
}

/******************************************************************************
* Returns a data item from the list data model.
******************************************************************************/
QVariant StructureListParameterUI::getItemData(RefTarget* target, const QModelIndex& index, int role)
{
	ParticleType* stype = dynamic_object_cast<ParticleType>(target);
	StructureIdentificationModifier* modifier = dynamic_object_cast<StructureIdentificationModifier>(editObject());

	if(stype && modifier) {
		if(role == Qt::DisplayRole) {
			if(index.column() == 1) {
				return stype->nameOrId();
			}
			else if(index.column() == 2) {
				if(_structureCounts && stype->id() >= 0 && stype->id() < _structureCounts->size())
					return _structureCounts->getInt64(stype->id());
			}
			else if(index.column() == 3) {
				if(_structureCounts && stype->id() >= 0 && stype->id() < _structureCounts->size()) {
					size_t totalCount = 0;
					for(auto c : _structureCounts->constInt64Range())
						totalCount += c;
					return QString("%1%").arg((double)_structureCounts->getInt64(stype->id()) * 100.0 / std::max((size_t)1, totalCount), 0, 'f', 1);
				}
			}
			else if(index.column() == 4) {
				return stype->id();
			}
		}
		else if(role == Qt::DecorationRole) {
			if(index.column() == 0)
				return (QColor)stype->color();
		}
		else if(role == Qt::CheckStateRole && _showCheckBoxes) {
			if(index.column() == 0)
				return stype->enabled() ? Qt::Checked : Qt::Unchecked;
		}
	}
	return {};
}

/******************************************************************************
* Returns the model/view item flags for the given entry.
******************************************************************************/
Qt::ItemFlags StructureListParameterUI::getItemFlags(RefTarget* target, const QModelIndex& index)
{
	if(index.column() == 0 && _showCheckBoxes)
		return RefTargetListParameterUI::getItemFlags(target, index) | Qt::ItemIsUserCheckable;
	else
		return RefTargetListParameterUI::getItemFlags(target, index);
}

/******************************************************************************
* Sets the role data for the item at index to value.
******************************************************************************/
bool StructureListParameterUI::setItemData(RefTarget* target, const QModelIndex& index, const QVariant& value, int role)
{
	if(index.column() == 0 && role == Qt::CheckStateRole) {
		if(ParticleType* stype = static_object_cast<ParticleType>(objectAtIndex(index.row()))) {
			bool enabled = (value.toInt() == Qt::Checked);
			undoableTransaction(tr("Enable/disable structure type"), [stype, enabled]() {
				stype->setEnabled(enabled);
			});
			return true;
		}
	}

	return RefTargetListParameterUI::setItemData(target, index, value, role);
}

/******************************************************************************
* Is called when the user has double-clicked on one of the structure
* types in the list widget.
******************************************************************************/
void StructureListParameterUI::onDoubleClickStructureType(const QModelIndex& index)
{
	// Let the user select a color for the structure type.
	ParticleType* stype = static_object_cast<ParticleType>(selectedObject());
	if(!stype) return;

	QColor oldColor = (QColor)stype->color();
	QColor newColor = QColorDialog::getColor(oldColor, editor()->container());
	if(!newColor.isValid() || newColor == oldColor) return;

	undoableTransaction(tr("Change structure type color"), [stype, newColor]() {
		stype->setColor(Color(newColor));
	});
}

OVITO_END_INLINE_NAMESPACE
OVITO_END_INLINE_NAMESPACE
}	// End of namespace
}	// End of namespace
