# This module tries to find the libssh library.
#
# It creates an imported CMake target named "Libssh::Libssh".

FIND_PATH(LIBSSH_INCLUDE_DIR NAMES libssh/libssh.h)
FIND_LIBRARY(LIBSSH_LIBRARY NAMES ssh libssh)
SET(LIBSSH_INCLUDE_DIRS ${LIBSSH_INCLUDE_DIR})
SET(LIBSSH_LIBRARIES ${LIBSSH_LIBRARY})
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBSSH DEFAULT_MSG LIBSSH_LIBRARY LIBSSH_INCLUDE_DIR)
MARK_AS_ADVANCED(LIBSSH_INCLUDE_DIR LIBSSH_LIBRARY)

# Create imported target for the library.
IF(LIBSSH_FOUND AND NOT TARGET Libssh::Libssh)
	ADD_LIBRARY(Libssh::Libssh UNKNOWN IMPORTED)
	SET_TARGET_PROPERTIES(Libssh::Libssh PROPERTIES
		IMPORTED_LOCATION "${LIBSSH_LIBRARY}"
		INTERFACE_INCLUDE_DIRECTORIES "${LIBSSH_INCLUDE_DIR}"
	)
ENDIF()
